### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by palangappa** [abrohit/CryptoTrader-Bot#3]
**I runned the script, i got this error:**

`C:\Users\palan\Downloads\'\CryptoTrader-Bot-main>python main.py

DevTools listening on ws://127.0.0.1:52124/devtools/browser/71063c57-7ede-42f4-821e-99e8a2033974
[0614/165940.256:INFO:CONSOLE(126)] "not loaded module js/expected-language", source: https://in.tradingview.com/static/bundles/category.f5f42c4d36086721c1fe.js (126)
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    RSI = GetRSI()
  File "main.py", line 30, in GetRSI
    timeFrame = driver.find_element_by_xpath('/html/body/div[2]/div[5]/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div/div[1]/div/div/div[1]/div/div/div[2]')
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div[5]/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div/div[1]/div/div/div[1]/div/div/div[2]"}
  (Session info: headless chrome=91.0.4472.101)`

**Here is the part of the code:**
`

    url = 'https://in.tradingview.com/symbols/' + ticker + '/technicals/'

    option = webdriver.ChromeOptions()
    option.add_argument('headless')

    driver = webdriver.Chrome('D:\\chromedriver_win32\\chromedriver.exe', options=option)#Selenium Path.
    driver.get(url)

    timeFrame = driver.find_element_by_xpath('/html/body/div[2]/div[5]/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div/div[1]/div/div/div[1]/div/div/div[2]')
    timeFrame.click()

    time.sleep(0.5)
    
    soup=BeautifulSoup(driver.page_source,'lxml')
    
    driver.quit()
    
    RSI = float(soup.findAll("td", {"class": "cell-5XzWwbDG"})[1].get_text())
    return(RSI)`

**Comment by palangappa** [comment]
@abrohit  any updates regarding this?

**Comment by abrohit** [comment]
Looks like TradingView has updated their website. Will push a fix asap.

**Comment by palangappa** [comment]
@abrohit any update regarding the issues?

**Comment by eklavyadev** [comment]
hey @abrohit, the script buys BTC at market price and sells it when it goes above it? What is the logic behind?
